sudo: required
services:
  - docker

before_install:
  - docker build -t  msi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true msi/react-test npm test
  

after_success:
  - docker build -t msi/multi-client ./client
  - docker build -t msi/multi-nginx ./nginx
  - docker build -t msi/multi-server ./server
  - docker build -t msi/multi-worker ./worker  
  #login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to dockerhub
  - docker push msi/multi-client
  - docker push msi/multi-nginx
  - docker push msi/multi-server
  - docker push msi/multi-worker
